- name: copy redis service file
  template:
    src: redis.service
    dest: /usr/lib/systemd/system/redis.service
    mode: '0644'
  register: info_service

- name: systemctl daemon-reload
  shell: systemctl daemon-reload
  when: info_service.changed

- name: copy redis config file
  template:
    src: redis.conf
    dest: /etc/redis.conf
    group: root
    owner: redis
    mode: '0640'
  notify: restart redis 

- name: start redis
  service:
    name: redis
    state: started
    enabled: yes
