- name: Install the compilation environment package
  yum:
    name:
      - gcc-c++
      - tcl
    state: present

- name: create redis user
  user:
    comment: Redis Database Server
    home: /var/lib/redis
    shell: /sbin/nologin
    user: redis
    system: yes
    state: present

- name: create redis log and run directory
  file:
    path: "{{item}}"
    state: directory
    group: redis
    owner: redis 
    mode: '0755'
  with_items:
    - /var/log/redis
    - /var/run/redis

- name: Copy the redis binary file
  copy:
    src: bin/
    dest: /usr/bin/
    mode: '0755'

- name: link redis-sentinel 
  file:
    src: /usr/bin/redis-server
    dest: /usr/bin/redis-sentinel
    state: link

- name: overcommit_memory is set to 1
  sysctl:
    name: vm.overcommit_memory
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes

- name: THP is disabled 
  blockinfile:
    path: /etc/rc.local
    block: "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
    state: present
  notify: source /etc/rc.local
