- name: copy sentinel service file
  template:
    src: redis-sentinel.service
    dest: /usr/lib/systemd/system/redis-sentinel.service
    mode: '0644'
  register: info_service

- name: systemctl daemon-reload
  shell: systemctl daemon-reload
  when: info_service.changed

- name: copy sentinel config file
  template:
    src: sentinel.conf
    dest: /etc/redis-sentinel.conf
    group: root
    owner: redis
    mode: '0640'
  notify: restart redis-sentinel

- name: start redis-sentinel
  service:
    name: redis-sentinel
    state: started
    enabled: yes
